---
version: "3"

services:
  test_db_postgres:
    container_name: DB_Postgres
    image: postgres:13.3
    env_file: .env
    ports:
      - 5556:5432
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d TestTaskDbContext" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - .\\volumes\\postgres-data\\:/var/lib/postgresql/data

  test_service_postgres_migrator:
    container_name: BackendTestTask_Postgres_Migrator
    build:
      context: ./../
      dockerfile: ./src/BackendTestTask.DatabaseMigrator/Dockerfile
    env_file: .env
    command:
       [
        "dotnet",
        "BackendTestTask.DatabaseMigrator.dll",
        "--connection-string-source=env",
        "--connection-string-env-variable-name=BackendTestTask_ConnectionStrings__TestTaskDbContext"
      ]
    depends_on:
      test_db_postgres:
        condition: service_healthy